version: '3.7'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.66.0/24

volumes:
  cs-ansible:

services:
  kdms1:
    image: agupta73/kdms
    ports:
       - "801:80"
    networks:
      custom:
        ipv4_address: 192.168.66.11
    dns: 8.8.8.8
    container_name: uikdms1
    hostname: kdms
    restart: always
    
  kdms2:
    image: agupta73/kdms
    ports:
       - "802:80"
    networks:
      custom:
        ipv4_address: 192.168.66.12
    dns: 8.8.8.8
    container_name: uikdms2
    hostname: kdms
    restart: always
    
  kdms_db:
    image: agupta73/dbkdms
    ports:
      - "3301:3306"
    networks:
      custom:
        ipv4_address: 192.168.66.13
    dns: 8.8.8.8
    container_name: dbkdms
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
       - type: bind
         source: ../cKDMS/db/MySQL_Conf/my.cnf
         target: /etc/my.cnf
       - type: bind
         source: ../cKDMS/db/MySQL_Data
         target: /var/lib/mysql
    hostname: kdms_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    
# CREATE USER 'root'@'%' IDENTIFIED BY 'password'
# GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER, CREATE TABLESPACE, CREATE ROLE, DROP ROLE ON *.* TO `root`@`%` WITH GRANT OPTION                                                                                       |
# GRANT APPLICATION_PASSWORD_ADMIN,AUDIT_ADMIN,BACKUP_ADMIN,BINLOG_ADMIN,BINLOG_ENCRYPTION_ADMIN,CLONE_ADMIN,CONNECTION_ADMIN,ENCRYPTION_KEY_ADMIN,GROUP_REPLICATION_ADMIN,INNODB_REDO_LOG_ARCHIVE,PERSIST_RO_VARIABLES_ADMIN,REPLICATION_SLAVE_ADMIN,RESOURCE_GROUP_ADMIN,RESOURCE_GROUP_USER,ROLE_ADMIN,SERVICE_CONNECTION_ADMIN,SESSION_VARIABLES_ADMIN,SET_USER_ID,SYSTEM_USER,SYSTEM_VARIABLES_ADMIN,TABLE_ENCRYPTION_ADMIN,XA_RECOVER_ADMIN ON *.* TO `root`@`%` WITH GRANT OPTION |
# GRANT ALL PRIVILEGES ON `table`.* TO `root`@`%` WITH GRANT OPTION                                                                                                                                                                                                                                                                                                                                                                                                                      |
# GRANT PROXY ON ''@'' TO 'root'@'%' WITH GRANT OPTION  