version: '3.7'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.66.0/24

volumes:
  cs-ansible:

services:
  kdms1:
    image: agupta73/kdms
    ports:
       - "8095:80"
    networks:
      custom:
        ipv4_address: 192.168.66.11
    dns: 8.8.8.8
    container_name: uikdms1
    hostname: kdms
    restart: always
    
  kdms2:
    image: agupta73/kdms
    ports:
       - "8096:80"
    networks:
      custom:
        ipv4_address: 192.168.66.12
    dns: 8.8.8.8
    container_name: uikdms2
    hostname: kdms
    restart: always
    
  kdms_db:
    image: agupta73/dbkdms
    ports:
      - "3309:3306"
    networks:
      custom:
        ipv4_address: 192.168.66.13
    dns: 8.8.8.8
    container_name: dbkdms
    volumes:
       - type: bind
         source: /Users/agupta/MySQL_Conf/my.cnf
         target: /etc/my.cnf
       - type: bind
         source: /Users/agupta/MySQL_Data
         target: /var/lib/mysql
    hostname: kdms_db
    restart: always
    
